version: '3.8'

services:
  backend:
    build: .
    env_file:
      - .env
    volumes:
      - static_vol:/proveeagro/backend/static
    ports:
      - "8000:8000"
  
  nginx:
    build: ./nginx
    volumes:
      - static_vol:/proveeagro/backend/static
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  static_vol:
