# Generated by Django 5.0.2 on 2024-03-29 05:51



from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
