# Generated by Django 5.0.2 on 2024-04-01 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_supplier_latitude_remove_supplier_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='id_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_location', to='dashboard.location', verbose_name='Location'),
            preserve_default=False,
        ),
    ]
