# Generated by Django 5.0.2 on 2024-04-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_supplier_id_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
    ]
