# Generated by Django 5.0.3 on 2024-04-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_id_department_city_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default=1, max_length=250, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(default=1, max_length=250, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
