# Generated by Django 5.0.2 on 2024-04-27 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Crop Type')),
            ],
            options={
                'verbose_name': 'Crop Type',
                'verbose_name_plural': 'Crop Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Livestock_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Livestock Type')),
            ],
            options={
                'verbose_name': 'Livestock Type',
                'verbose_name_plural': 'Livestock Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BooleanField(default=False, verbose_name='Crop Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.crop_type', verbose_name='Crop Type')),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BooleanField(default=False, verbose_name='Livestock Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('livestock_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.livestock_type', verbose_name='Livestock Type')),
            ],
            options={
                'verbose_name': 'Livestock',
                'verbose_name_plural': 'Livestocks',
                'ordering': ['name'],
            },
        ),
    ]
