# Generated by Django 5.1 on 2024-09-08 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0009_alter_farm_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'ordering': ['name'], 'verbose_name': 'Granja', 'verbose_name_plural': 'Granjas'},
        ),
        migrations.AlterModelOptions(
            name='farmactivity',
            options={'ordering': ['farm'], 'verbose_name': 'Actividad de la granja', 'verbose_name_plural': 'Actividades de la granja'},
        ),
        migrations.AlterModelOptions(
            name='farmsupplier',
            options={'ordering': ['farm'], 'verbose_name': 'Proveedor de la granja', 'verbose_name_plural': 'Proveedores de la granja'},
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre de la granja'),
        ),
        migrations.AlterField(
            model_name='farmactivity',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm', verbose_name='Granja'),
        ),
        migrations.AlterField(
            model_name='farmsupplier',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm', verbose_name='Granja'),
        ),
    ]
