# Generated by Django 5.1 on 2024-10-03 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0010_alter_farm_options_alter_farmactivity_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='user',
            new_name='created_by',
        ),
    ]
