# Generated by Django 5.1 on 2024-10-07 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0011_rename_user_farm_created_by'),
        ('suppliers', '0004_remove_city_department_remove_location_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_count', models.IntegerField(default=0)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
        ),
    ]
