# Generated by Django 5.1 on 2024-12-12 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0015_historicalfarmsupplier'),
        ('suppliers', '0005_historicalsupplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la categoría')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del insumo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='farms.category', verbose_name='Categoría')),
                ('farms', models.ManyToManyField(blank=True, related_name='supplies', to='farms.farm', verbose_name='Granjas relacionadas')),
                ('suppliers', models.ManyToManyField(blank=True, related_name='supplies', to='suppliers.supplier', verbose_name='Proveedores relacionados')),
            ],
        ),
    ]
