# Generated by Django 5.1 on 2024-12-17 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0016_category_supply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='farms',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='suppliers',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Supply',
        ),
    ]
